name: Build Release Zip

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package

      #    - name: Zip JAR with Levels folder
      #      run: |
      #        zip -j Vehicle2redux.zip target/*.jar
      #        zip -r Vehicle2redux.zip Levels/

      - name: Copy Files
        run: |
          mkdir ./Vehicle2redux
          cp -r ./target/Vehicle2-redux-1.0-SNAPSHOT.jar ./Vehicle2redux/
          cp -r ./Levels/* ./Vehicle2redux/
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Vehicle2redux
          path: |
            Vehicle2redux/
          # **/Vehicle2-redux-1.0-SNAPSHOT.jar
          # Levels/
